### PR TITLE
Fix a concurrent modification error during reconnection

### LINKED ISSUE #43: The subscribe method of Dart SDK throws error after few seconds.
I am using the Dart SDK. So, when I subscribe the collection to kuzzle. It works fine but after few seconds it may tries to re-subscribe the collection (this is our assumption). 
**So after few seconds it throws the following error in subscribe method only.**
```


E/flutter (30105): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Concurrent modification during iteration: Instance(length:43) of '_GrowableList'.
E/flutter (30105): #0      ListIterator.moveNext (dart:_internal/iterable.dart:337:7)
E/flutter (30105): #1      RealTimeController._renewSubscribe (package:kuzzle/src/controllers/realtime.dart:159:25)
E/flutter (30105): <asynchronous suspension>
E/flutter (30105): #2      Function._apply (dart:core-patch/function_patch.dart:11:30)
E/flutter (30105): #3      Function.apply (dart:corepatch/function_patch.dart:34:12)
E/flutter (30105): #4      KuzzleEventEmitter.emit (package:kuzzle/src/kuzzle/event_emitter.dart:143:18)
E/flutter (30105): #5      Kuzzle.connect.<anonymous closure>.<anonymous closure> (package:kuzzle/src/kuzzle.dart:232:9)
E/flutter (30105): #6      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (30105): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (30105): #8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (30105): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (30105): #10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (30105): #11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
```

### PR DESCRIPTION
**Pull request by rafay-tariq**
## What does this PR do ?
It gives the error when the app is reconnected to the server

fix #43 

### How should this be manually tested?

  Updated File: "C:\flutter\.pub-cache\hosted\pub.dartlang.org\kuzzle-2.0.1\lib\src\controllers\realtime.dart"
  ...

### CODE REVIEW

**Comment by Aschen** [comment]
Hi @rafay-tariq !

Thanks you very much for your contribution :sunglasses:

File: lib/src/controllers/realtime.dart [hunk 1]
```diff
@@ -144,9 +144,13 @@ class RealTimeController extends KuzzleController {
             _currentSubscriptions[channel] = item;
             _subscriptionsCache[channel] = item;
           } else {
+            if (!_currentSubscriptions[channel].contains(subscription)) {
             _currentSubscriptions[channel].add(subscription);
+          }
+          if (!_subscriptionsCache[channel].contains(subscription)) {
             _subscriptionsCache[channel].add(subscription);
           }
+          }
```
Comment (Aschen) [inline lib/src/controllers/realtime.dart]: Bad indentation
```suggestion
          } else {
            if (!_currentSubscriptions[channel].contains(subscription)) {
              _currentSubscriptions[channel].add(subscription);
            }
            if (!_subscriptionsCache[channel].contains(subscription)) {
              _subscriptionsCache[channel].add(subscription);
            }
          }
```

File: lib/src/controllers/realtime.dart [hunk 2]
```diff
@@ -156,7 +160,9 @@ class RealTimeController extends KuzzleController {
 
   void _renewSubscribe() async {
     for (final subs in _subscriptionsCache.values) {
-      for (final sub in subs) {
+       final List<Subscription> _localSubs = List<Subscription>.from(subs);
+        subs.clear();
```
Comment (Aschen) [inline lib/src/controllers/realtime.dart]: Can you fix the indentation here as well please? I can't do it from Github since the rest of the `subscribe` method is not in the diff

**Review by Aschen — CHANGES_REQUESTED** [review]
Minor indentation fixes

**Comment by Aschen** [comment]
You also need to merge the `2-dev` branch into yours to fix the CI

File: lib/src/controllers/realtime.dart (hunk 2 above)
Comment (rafay-tariq) [reply lib/src/controllers/realtime.dart]: I have fixed the indentation.

**Review by Aschen — APPROVED** [review]

**Comment by y-abs** [comment]
@rafay-tariq Thank you for your contribution!
Can you please rebase your branch on the 2-dev branch and push please (`git checkout patch-1`, `git rebase 2-dev`) ? It seems that you pulled your branch from master
