### PR TITLE
Fix autoreconnect

### LINKED ISSUE #83: Automatic Reconnection after connection lost
## Description

Hello, 
I am using Dart SDK v2.4.1 with Flutter. 
I am having problem with automatic reconnection to Kuzzle Backend. First issue is when I simulate network disconnection (by turning WiFi  'off') I don't get kuzzle.on('disconnected') event. Second problem is after turning WiFi 'on' it takes few minutes to reconnect. It should last much shorter like for example in JavaScript SDK (it reconnects in few seconds). And then, when it eventually reconnects, it keep emitting  kuzzle.on('reconnected') event every few seconds.

I am using following constructor:          

final kuzzle = new Kuzzle(
  WebSocketProtocol(
    Uri(
      scheme: 'ws',
      host: 'kuzzle_ipaddress',
      port: 7512,
    ),
    autoReconnect: true,
    reconnectionDelay: Duration(milliseconds: 1000),
    pingInterval: Duration(milliseconds: 2000),
  ),
  offlineMode: OfflineMode.manual,
);

## Context (Environment)
SDK version 2.4.1

### PR DESCRIPTION
**Pull request by jenow**
## What does this PR do ?

fixes #83 

The `disconnected` event was not thrown in case of a manual disconnect.
Also the auto reconnection logic was not working. I moved the logic of the reconnection from the abstract protocol class to the actual websocket protocol and now call the `reconnected` event.

### CODE REVIEW

File: lib/src/protocols/websocket_io.dart [hunk 1]
```diff
@@ -81,7 +85,7 @@ class KuzzleWebSocket extends KuzzleProtocol {
     super.close();
 
     removeAllListeners();
-    stopRetryingToConnect = true;
+    _stopRetryingToConnect = true;
```
Comment (Shiranuit) [inline lib/src/protocols/websocket_io.dart:101]: On close this variable is set to true to cancel future reconnection attempt but this is never set back to false, meaning that if you do close the connection at one point, then do a connect and it fails, the auto reconnect wont work because of `_stopRetryingToConnect` being `true`

you should reset it back to false at some point

**Review by Shiranuit — CHANGES_REQUESTED** [review]

File: lib/src/protocols/websocket_io.dart [hunk 2]
```diff
@@ -65,6 +65,7 @@ class KuzzleWebSocket extends KuzzleProtocol {
         onError: _handleError, onDone: _handleDone);
 
     clientConnected();
+    _stopRetryingToConnect = false;
```
Comment (Shiranuit) [inline lib/src/protocols/websocket_io.dart]: I think there is one more edge case, here you reset it back when the connection is successful, meaning that, in the case of [`current connection` -> `close()` -> `connect()` -> `connection fails`], the variable `_stopRetryingToConnect` will be `false` preventing the auto reconnection attempts

**Review by Shiranuit — CHANGES_REQUESTED** [review]

File: lib/src/protocols/websocket_io.dart (hunk 2 above)
Comment (jenow) [reply lib/src/protocols/websocket_io.dart]: If you close the connection then it does not make sense to have the reconnection attempts. To have reconnection attempts you first need to be connected (_stopRetryingToConnect will then be false), have a disconnection and then it will start trying  to reconnect.

Comment (Shiranuit) [reply lib/src/protocols/websocket_io.dart]: I've searched across some of our SDKs, and the current behaviour is if a connection fails and the autoReconnect is `true` start a reconnection attempt, even if that was the first connection.

This is even the case here in the dark  SDK
```dart
if (wasConnected || autoReconnect) {
        clientNetworkError(
            KuzzleError('WebSocketProtocol: Unable to connect to $url'));
        _handleAutoReconnect();
}
````

**Edit: This doesn't seem to be the case everywhere though,  e.g  SDK-JS**

**Edit2: I was thinking that wasn't the case for the Javascript-SDK but in fact it is, and there is something strange, the SDK-JS only do one reconnection attempt in case of failure**

**Review by Shiranuit — APPROVED** [review]

**Review by Shiranuit — APPROVED** [review]

**Review by y-abs — APPROVED** [review]
